#!/bin/bash

# Võtan analüüsi laused, kus sisaldub sõna "apartheid"
# Asendan realõpud märgiga #, et hiljem saaks sõnapaaride analüüsis piirduda ühe lausega.
# Kustutan üleliigsed märgendid.
# Asendan tühikud reavahetustega, et igal real oleks üks sõna.
# Kustutan tühjaks jäänud read.
# Lisan iga lause lõppu neli tühikut, et oleks võimalik moodustada sõnapaare.

grep 'apartheid' \
| tr '[A-Z]' '[a-z]' \
| sed 's/$/#/' \
| tr -d '\.\,\?\!\:\"\“\”\(\)\;' \
| tr ' ' '\n' \
| grep -v '^$' \
| sed 's/#/\n\n\n\n\n/' > read.txt

# Kustutan faili esimese sõna ja kordan seda tegevust veel viis korda, et analüüsitavate sõnapaaride vahel oleks 0-5 sõna.

cat read.txt | tail -n +2 > read-1.txt
cat read.txt | tail -n +3 > read-2.txt
cat read.txt | tail -n +4 > read-3.txt
cat read.txt | tail -n +5 > read-4.txt
cat read.txt | tail -n +6 > read-5.txt
cat read.txt | tail -n +7 > read-6.txt

# Lisan kõik tekkinud sõnapaarid ühte sõnapaaride faili.

paste read.txt read-1.txt > paarid.txt
paste read.txt read-2.txt >> paarid.txt
paste read.txt read-3.txt >> paarid.txt
paste read.txt read-4.txt >> paarid.txt
paste read.txt read-5.txt >> paarid.txt
paste read.txt read-6.txt >> paarid.txt

# Analüüsin ainult neid sõnapaare, milles sisaldub sõna "apartheid".
# Asendan need tulemused, kus paare ei moodustunud, märgiga # ja siis kustutan need read.
# Asendan paaride vahed reavahega, et jätta analüüsiks alles vaid sõnaga "apartheid" koos esinevad sõnad.
# Sorteerin tulemused esinemise sageduse järjekorras.

cat paarid.txt \
| grep '[^\t]*apartheid[^\t]*' \
| sed 's/^.*apartheid.*\t$/#/' \
| sed 's/^\t.*apartheid.*$/#/' \
| grep -v '#' \
| tr '\t' '\n' \
| grep -v 'apartheid' \
| sort | uniq -c | sort -nr
